# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    uses: './.github/workflows/build.yml'
    with:
      target_ref: '${{ github.ref_name }}'
      build_mode: 'nightly'
      generate_version: true

  steam-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: out/
      
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.CONFIGVDF}}          
          appId: 2108550
          buildDescription: 'Automatic deployment'
          rootPath: out/
          depot3Path: build-win32
          depot4Path: build-linux
          depot5Path: build-osx
          releaseBranch: nightly
  
  linux:
    needs: build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-linux
        path: out/

    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'inochi-creator-linux-x86_64.zip'
        directory: 'out/'
        path: '*'

    - name: Release to nightly tag
      uses: softprops/action-gh-release@v1
      with:
        name: 'Nightly Build'
        tag_name: nightly
        files: |
          out/inochi-creator-linux-x86_64.zip
        generate_release_notes: true

  windows:
    needs: build
    runs-on: windows-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-win32
        path: out/
    
    - uses: actions/checkout@v4.1.7
      with:
        sparse-checkout:
          build-aux
    
    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'inochi-creator-win32-x86_64.zip'
        directory: 'out/'
        path: '*'

    - name: 'Add msbuild to PATH'
      uses: microsoft/setup-msbuild@v1.1
    
    - name: 'Build MSI'
      run: |
        cd build-aux/windows/wix

        # Install required dependency
        mkdir packages/
        nuget install WixToolset.UI.wixext -version 4.0.0 -OutputDirectory packages/

        # Build solution
        msbuild "Inochi Creator.sln" -property:Configuration=Release

        # Copy installer out
        mv "bin/Release/Inochi Creator.msi" "../../../out/inochi-creator-win32-x86_64.msi"
        cd ../../../

    - name: 'Release to nightly tag'
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: nightly
        files: |
          out/inochi-creator-win32-x86_64.msi
          out/inochi-creator-win32-x86_64.zip

  macOS:
    needs: build
    runs-on: macos-14

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-osx
        path: out/
    
    - uses: actions/checkout@v4.1.7
      with:
        sparse-checkout:
          build-aux

    - name: 'Build DMG'
      run: |
        ./build-aux/osx/gendmg.sh

    - name: Release to nightly tag
      uses: softprops/action-gh-release@v1
      with:
        name: 'Nightly Build'
        tag_name: nightly
        files: 'out/Install_Inochi_Creator.dmg'

  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged

    env:
      MANIFEST_PATH: build-aux/flatpak/nightly/com.inochi2d.inochi-creator.yml
      FLATPAK_BRANCH: nightly
      FLATPAK_BUILD_DIR: build-dir
      FLATPAK_BUILD_REPO: build-repo

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        submodules: true

    - name: Dump canonical manifest
      run: |
        set -e
        flatpak-builder --show-manifest ${MANIFEST_PATH} > canonical-manifest.json

    - name: Download flatpak SDK and sources
      run: |
        set -e
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --install-deps-from=flathub --install-deps-only --user /dev/null ${MANIFEST_PATH}
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --download-only /dev/null ${MANIFEST_PATH}

    - name: Prime cache
      uses: actions/cache@v3
      with:
        path: |
          .flatpak-builder/ccache
        key: flatpak-builder-${{ hashFiles('canonical-manifest.json') }}
        restore-keys: |
          flatpak-builder-

    - name: Build flatpak
      run: |
        set -e
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --ccache --repo=${FLATPAK_BUILD_REPO} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}

    - name: Upload flatpak repo
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FLATPAK_BUILD_REPO }}
        path: |
          ${{ env.FLATPAK_BUILD_REPO }}
          !${{ env.FLATPAK_BUILD_REPO }}/.lock

  publish-flatpak-bundle:
    runs-on: ubuntu-latest
    needs: build-flatpak

    env:
      APP_ID: com.inochi2d.inochi-creator
      FLATPAK_BUNDLE: inochi-creator
      FLATPAK_BRANCH: nightly
      FLATPAK_BUILD_REPO: build-repo

    steps:
    - uses: actions/checkout@v2

    - name: Install flatpak
      run: |
        set -e
        sudo apt install -y flatpak

    - name: Download flatpak repo
      uses: actions/download-artifact@v1
      with:
        name: ${{ env.FLATPAK_BUILD_REPO }}

    - name: Create flatpak bundle
      run: |
        set -e
        mkdir -p ${FLATPAK_BUILD_REPO}/{extensions,refs/{mirrors,remotes},state,tmp/cache}
        flatpak build-bundle --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo ${FLATPAK_BUILD_REPO} ${FLATPAK_BUNDLE}.flatpak ${APP_ID} ${FLATPAK_BRANCH}

    - name: Release to nightly tag
      uses: softprops/action-gh-release@v1
      with:
        name: 'Nightly Build'
        tag_name: nightly
        files: |
          ${{ env.FLATPAK_BUNDLE }}.flatpak

