name: 'Publish to GitHub'

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        default: ${{ github.ref }}
      name:
        required: true
        type: string
      generate-notes:
        required: false
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: build-*-
        merge-multiple: true
        path: builds/

    - name: 'Release to ${{ inputs.tag }}'
      uses: softprops/action-gh-release@v1
      with:
        name: '${{ inputs.name }}'
        tag_name: ${{ inputs.tag }}
        files: |
          builds/out/inochi-creator-linux.zip
          builds/out/inochi-creator-win32.zip
          builds/out/inochi-creator-osx.zip
          builds/out/inochi-creator-win32.msi
          builds/out/Install_Inochi_Creator.dmg
        generate_release_notes: ${{ inputs.generate-notes }}