# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build and Release (Nightly)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    uses: './.github/workflows/build.yml'
    with:
      target_ref: '${{ github.ref_name }}'
      variant: 'nightly'
      generate_version: true

  steam-publish:
    needs: build
    uses: './.github/workflows/publish-steam.yml'
    secrets: inherit
    with:
      branch: 'nightly'
  
  gh-publish:
    needs: build
    uses: './.github/workflows/publish-gh.yml'
    secrets: inherit
    with:
      tag: 'nightly'
      name: 'Nightly'
      generate-notes: true